BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Banestrekning" (
	"Navn"	TEXT NOT NULL,
	"Fremdriftsenergi"	TEXT NOT NULL,
	PRIMARY KEY("Navn")
);
CREATE TABLE IF NOT EXISTS "Stasjon" (
	"Navn"	TEXT NOT NULL,
	"Høyde"	INTEGER NOT NULL,
	PRIMARY KEY("Navn")
);
CREATE TABLE IF NOT EXISTS "Delstrekning" (
	"StartstasjonNavn"	TEXT NOT NULL,
	"EndestasjonNavn"	TEXT NOT NULL,
	"Lengde"	INTEGER NOT NULL,
	"ErEnkeltspor"	INTEGER NOT NULL,
	"BanestrekningNavn"	TEXT,
	PRIMARY KEY("StartstasjonNavn","EndestasjonNavn"),
	FOREIGN KEY("EndestasjonNavn") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("BanestrekningNavn") REFERENCES "Banestrekning"("Navn") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("StartstasjonNavn") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Operator" (
	"Operatornavn"	TEXT NOT NULL,
	PRIMARY KEY("Operatornavn")
);
CREATE TABLE IF NOT EXISTS "Togrute" (
	"RuteID"	INTEGER NOT NULL,
	"OperatorNavn"	TEXT NOT NULL,
	"Hovedretning"	INTEGER NOT NULL,
	"StartstasjonNavn"	TEXT NOT NULL,
	"EndestasjonNavn"	TEXT NOT NULL,
	PRIMARY KEY("RuteID"),
	FOREIGN KEY("EndestasjonNavn") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("StartstasjonNavn") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("OperatorNavn") REFERENCES "Operator"("Operatornavn") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "PaRute" (
	"StasjonNavn"	TEXT NOT NULL,
	"RuteID"	INTEGER NOT NULL,
	"Ankomsttid"	INTEGER,
	"Avgangstid"	INTEGER,
	PRIMARY KEY("StasjonNavn","RuteID"),
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("StasjonNavn") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "RutePaUkedag" (
	"RuteID"	INTEGER NOT NULL,
	"Ukedag"	INTEGER NOT NULL,
	PRIMARY KEY("RuteID","Ukedag"),
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "RutePaStrekning" (
	"RuteID"	INTEGER NOT NULL,
	"Startstasjon"	TEXT NOT NULL,
	"Endestasjon"	TEXT NOT NULL,
	PRIMARY KEY("RuteID","Startstasjon","Endestasjon"),
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("Startstasjon") REFERENCES "Stasjon"("Navn") ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY("Endestasjon") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Stol" (
	"VognID"	INTEGER NOT NULL,
	"StolNr"	INTEGER NOT NULL,
	PRIMARY KEY("VognID","StolNr"),
	FOREIGN KEY("VognID") REFERENCES "Sittevogn"("VognID") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Kupe" (
	"VognID"	INTEGER NOT NULL,
	"KupeNr"	INTEGER NOT NULL,
	PRIMARY KEY("VognID","KupeNr"),
	FOREIGN KEY("VognID") REFERENCES "Vogn"("VognID") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Seng" (
	"VognID"	INTEGER NOT NULL,
	"SengNr"	INTEGER NOT NULL,
	"KupeNr"	INTEGER NOT NULL,
	PRIMARY KEY("VognID","SengNr"),
	FOREIGN KEY("KupeNr") REFERENCES "Kupe"("KupeNr") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("VognID") REFERENCES "Vogn"("VognID") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Kunde" (
	"KundeNr"	INTEGER NOT NULL,
	"Navn"	TEXT NOT NULL,
	"Epostadresse"	TEXT NOT NULL,
	"Mobilnummer"	INTEGER NOT NULL,
	PRIMARY KEY("KundeNr")
);
CREATE TABLE IF NOT EXISTS "TogruteForekomst" (
	"ForekomstID"	INTEGER NOT NULL,
	"Ukedag"	INTEGER NOT NULL,
	"TogruteID"	INTEGER NOT NULL,
	PRIMARY KEY("ForekomstID"),
	FOREIGN KEY("TogruteID") REFERENCES "Togrute"("RuteID") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Kundeordre" (
	"OrdreNr"	INTEGER NOT NULL,
	"ForekomstID"	INTEGER NOT NULL,
	"Kjøpsdag"	INTEGER NOT NULL,
	"Kjøpstid"	INTEGER NOT NULL,
	"KundeNr"	INTEGER NOT NULL,
	"StartStasjon"	TEXT NOT NULL,
	"EndeStasjon"	TEXT NOT NULL,
	PRIMARY KEY("OrdreNr"),
	FOREIGN KEY("KundeNr") REFERENCES "Kunde"("KundeNr") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("ForekomstID") REFERENCES "TogruteForekomst"("ForekomstID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("EndeStasjon") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("StartStasjon") REFERENCES "Stasjon"("Navn") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "SengeBillett" (
	"BilettNr"	INTEGER NOT NULL,
	"OrdreNr"	INTEGER NOT NULL,
	"SengNr"	INTEGER NOT NULL,
	"VognrNr"	INTEGER NOT NULL,
	PRIMARY KEY("BilettNr","OrdreNr"),
	FOREIGN KEY("OrdreNr") REFERENCES "Kundeordre"("OrdreNr") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "SitteBillett" (
	"BillettNr"	INTEGER NOT NULL,
	"OrdreNr"	INTEGER NOT NULL,
	"StolNr"	INTEGER NOT NULL,
	"VognNr"	INTEGER NOT NULL,
	PRIMARY KEY("BillettNr","OrdreNr"),
	FOREIGN KEY("OrdreNr") REFERENCES "Kundeordre"("OrdreNr") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Vogn" (
	"VognID"	INTEGER NOT NULL,
	"Type"	INTEGER NOT NULL,
	"Navn"	TEXT,
	"SengerPerKupe"	INTEGER,
	"StolerPerRad"	INTEGER,
	"OperatorNavn"	TEXT NOT NULL,
	PRIMARY KEY("VognID"),
	FOREIGN KEY("OperatorNavn") REFERENCES "Operator"("Operatornavn") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Vognoppsett" (
	"VognID"	INTEGER NOT NULL,
	"RuteID"	INTEGER NOT NULL,
	"VognNr"	INTEGER NOT NULL,
	PRIMARY KEY("VognID","RuteID"),
	FOREIGN KEY("VognID") REFERENCES "Vogn"("VognID") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("RuteID") REFERENCES "Togrute"("RuteID") ON DELETE CASCADE ON UPDATE CASCADE
);
COMMIT;
